# Group work I

In the first exercise, you learn how to interact with `pandas` library that is very useful for deadling with tabular data.
Moreover, you will have a first look at the data that we work with in the next session, the *Annotated Beethoven Corpus* (ABC).
The ABC contains harmonic annotations for all string quartets by Ludwig van Beethoven. The corpus is described in

* Neuwirth, M., Harasim, D., Moss, F. C.,  & Rohrmeier, M. (2018). The Annotated Beethoven Corpus (ABC): A Dataset of Harmonic Analyses of All Beethoven String Quartets. *Frontiers in Digital Humanities*. https://doi.org/10.3389/fdigh.2018.00016

A study based on this corpus is

* Moss, F. C., Harasim, D., Neuwirth, M., & Rohrmeier, M. (2019). Statistical characteristics of tonal harmony: A corpus study of Beethovenâ€™s string quartets. *PLOS ONE*. https://doi.org/10.1371/journal.pone.0217242

**Preparation**

1. Select one member of your team who shares her/his screen (maybe someone with *some* programming experience). 
2. Do all the exercises in that person's notebook together.

If you are not sure how to solve a task, Google is your friend. If you have any questions at any point, don't hesitate to ask me or Sebastian for help.

## Exercises

First, import the `pandas` library in the cell below. It is customary to abbreviate it with `pd`. If you are not sure how to do this, have a look at the ["10 minutes to pandas"](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) tutorial or ask Google.

In [1]:
import pandas as pd

You can check which version of `pandas` you are using by using the `.__version__` attribute of `pd`(two underscores on each side).

In [2]:
pd.__version__

'1.0.5'

The best way to learn how `pandas` works is to use it! The ABC is stored at the following address:

In [3]:
url = "https://raw.githubusercontent.com/DCMLab/ABC/master/data/all_annotations.tsv"

The most important object in `pandas` is a **DataFrame** which is basically just another word for a table.

We can load the ABC from the address that is stored in the variable `url` by passing it to the `.read_table()` method. Assign it to a variable called `abc`. The code for doing this is `abc = pd.read_table(url)`.

In [4]:
abc = pd.read_table(url)

Call the variable `abc` in the next cell.

In [5]:
abc

,chord,altchord,measure,beat,totbeat,timesig,op,no,mov,length,global_key,local_key,pedal,numeral,form,figbass,changes,relativeroot,phraseend
0,.Eb.I,NaN,1,1.0,1.0,2/4,127,12,1,2.5,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
1,V43,NaN,2,1.5,3.5,2/4,127,12,1,1.5,Eb,I,NaN,V,NaN,43.0,NaN,NaN,False
2,I,NaN,3,1.0,5.0,2/4,127,12,1,2.5,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
3,V2,NaN,4,1.5,7.5,2/4,127,12,1,1.5,Eb,I,NaN,V,NaN,2.0,NaN,NaN,False
4,I6,NaN,5,1.0,9.0,2/4,127,12,1,1.0,Eb,I,NaN,I,NaN,6.0,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28090,I,NaN,171,1.0,542.5,2/2,95,11,4,4.0,false,I,NaN,I,NaN,NaN,NaN,NaN,False
28091,V7,NaN,172,1.0,546.5,2/2,95,11,4,4.0,false,I,NaN,V,NaN,7.0,NaN,NaN,False
28092,I,NaN,173,1.0,550.5,2/2,95,11,4,4.0,false,I,NaN,I,NaN,NaN,NaN,NaN,False
28093,V,NaN,174,1.0,554.5,2/2,95,11,4,4.0,false,I,NaN,V,NaN,NaN,NaN,NaN,False
28094,I\\\\,NaN,175,1.0,558.5,2/2,95,11,4,4.0,false,I,NaN,I,NaN,NaN,NaN,NaN,True

As you can see, `pandas` displays the first and the last five rows, and a lot of columns of the table. A very handy way to know how large the table is, is to use the `.shape` attribute of the `abc` DataFrame. It returns a pair `(number_of_rows, number_of_columns)`. Use this attribute in the cell below and compare it to the numbers of rows and columns that are displayed directly below the DataFrame.

In [6]:
abc.shape

(28095, 19)

Now, try to figure out what the following columns could mean and write it to the code (like the example for `chord`).

In [7]:
column_meanings = """
chord: 'A chord symbol'
measure:
beat:
totbeat:
timesig:
op:
no:
mov:
length:
global_key:
local_key:
numeral:
figbass:
"""

We can look at individual columns of the DataFrame by **selecting** them. For example, if we had a DataFrame called `df` with a column named `temperature`, we could look at only this column by writing `df["temperature"]`. In the cell below, select the `chord` column of the DataFrame `abc`.

In [8]:
abc["chord"]

0        .Eb.I
1          V43
2            I
3           V2
4           I6
         ...
28090        I
28091       V7
28092        I
28093        V
28094    I\\\\
Name: chord, Length: 28095, dtype: object

Again, we see only the first and last five entries.

We know now how many chords are annotated in this corpus and how we can select individual columns. But how many *different* chords are there? `pandas` has a very useful method for this task, called `.value_counts()`. If you select the `chord` column in the DataFrame `abc` and append the `.value_counts()` method to it, it will show you the number of times each chord appears in the corpus in descending order.

In [9]:
abc["chord"].value_counts()

I            2672
V7           2087
V            1588
I6           1426
i             988
             ...
V6(4)/V         1
III.V[I         1
i64(119)        1
viio64(2)       1
iv(b6)          1
Name: chord, Length: 1730, dtype: int64

What are the five most common chords? Can you interpret it?

Now, in the big table that we have stored in the variable `abc` there are *all* chords in *all* of Beethoven's string quartets. What if we wanted to look only at a single of these quartets, for example the string quartet no. 11, op. 95 in F minor? The following code shows how we would do it:

```
abc[ abc["op"] == 95 ]
```

This reads as "Show me the `abc` where the `op` column of the `abc` is equal to 95 (note the double `==`). In the cell below, show only the rows of the table that belong to the string quartet no. 10, op. 74 in E$\flat$ major.

In [10]:
abc[ abc["op"] == 74 ]

,chord,altchord,measure,beat,totbeat,timesig,op,no,mov,length,global_key,local_key,pedal,numeral,form,figbass,changes,relativeroot,phraseend
25280,.Eb.I,NaN,1,1.00,1.00,4/4,74,10,1,2.00,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
25281,V2/IV,NaN,1,3.00,3.00,4/4,74,10,1,1.50,Eb,I,NaN,V,NaN,2.0,NaN,IV,False
25282,IV6,NaN,1,4.50,4.50,4/4,74,10,1,0.50,Eb,I,NaN,IV,NaN,6.0,NaN,NaN,False
25283,V43/IV,NaN,2,1.00,5.00,4/4,74,10,1,4.00,Eb,I,NaN,V,NaN,43.0,NaN,IV,False
25284,I,NaN,3,1.00,9.00,4/4,74,10,1,2.00,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26801,V6/V,NaN,207,1.75,412.75,2/4,74,10,4,0.25,Eb,I,NaN,V,NaN,6.0,NaN,V,False
26802,V7,NaN,207,2.00,413.00,2/4,74,10,4,1.00,Eb,I,NaN,V,NaN,7.0,NaN,NaN,False
26803,I,NaN,208,1.00,414.00,2/4,74,10,4,2.00,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
26804,V,NaN,209,1.00,416.00,2/4,74,10,4,2.00,Eb,I,NaN,V,NaN,NaN,NaN,NaN,False
26805,I\\\\,NaN,210,1.00,418.00,2/4,74,10,4,2.00,Eb,I,NaN,I,NaN,NaN,NaN,NaN,True

How could we now count all the chords in op. 74?

In [11]:
abc[ abc["op"] == 74 ]["chord"].value_counts()

I         146
V         123
V7        105
I6         61
V65        54
         ...
i6]         1
V43(2)      1
V(9)        1
I[I64       1
iv(b6)      1
Name: chord, Length: 272, dtype: int64

How many different chords are in op. 74? (Hint: You don't need to write code for that, the `.value_counts()` method already states it.

Above we have seen that the `global_key` contains the key of the entire piece, while `local_key` contains the keys to which a piece **modulates**. If we wanted to know which chords occur how often *either* in major *or* minor keys, we have to select them explicitly, similarly to how we selected an opus number. 

However, the DataFrame does not contain a `mode` column that would contain whether a chord occurs in a major or in a minor segment. But we can work around that! Let us first see, which local keys there are in all string quartets. This can be achieved by first selecting the `local_key` column and then calling the `.unique()` method on it.

In [12]:
abc["local_key"].unique()

array(['I', 'vi', 'iii', 'III', 'ii', 'VI', 'IV', 'V', '#V', '#iii', '#I',
       'bVII', 'i', 'bIII', 'v', 'II', '#iv', 'bVI', 'iv', '#i', 'vii',
       'VII', 'biii', 'bbII', 'bbV', 'bvii', 'bII', '#vii', '#II', '#III',
       'Ab', '#ii', '#IV', '#v', 'bI', 'bIV', 'bi', 'bV', 'bv', 'bii',
       '#VI'], dtype=object)

Apparently, there is a great variety of keys in Beethoven's string quartes. If we only want to select the major keys, we have to select all keys that start with an uppercase letter, e.g. `'VI'` **or** that start with a flat ($\flat$, here represented by the letter `b`) **and** have uppercase letters following, for example `'bIV'`. This is a quite complicated condition. For tasks like this, one can use so-called **regular expressions** (not necessary to know exactly what this means yet). The condition mentioned above would be expressed as follows:

In [13]:
major_condition = "^b?[A-Z]"

The `^b?` part means "has the letter 'b' at the beginning but only once", and the `[A-Z]` part means "any uppercase letter". Consequently, we can select all pieces in the major mode by

In [14]:
abc[ abc["local_key"].str.match(major_condition) ]

,chord,altchord,measure,beat,totbeat,timesig,op,no,mov,length,global_key,local_key,pedal,numeral,form,figbass,changes,relativeroot,phraseend
0,.Eb.I,NaN,1,1.0,1.0,2/4,127,12,1,2.5,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
1,V43,NaN,2,1.5,3.5,2/4,127,12,1,1.5,Eb,I,NaN,V,NaN,43.0,NaN,NaN,False
2,I,NaN,3,1.0,5.0,2/4,127,12,1,2.5,Eb,I,NaN,I,NaN,NaN,NaN,NaN,False
3,V2,NaN,4,1.5,7.5,2/4,127,12,1,1.5,Eb,I,NaN,V,NaN,2.0,NaN,NaN,False
4,I6,NaN,5,1.0,9.0,2/4,127,12,1,1.0,Eb,I,NaN,I,NaN,6.0,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28090,I,NaN,171,1.0,542.5,2/2,95,11,4,4.0,false,I,NaN,I,NaN,NaN,NaN,NaN,False
28091,V7,NaN,172,1.0,546.5,2/2,95,11,4,4.0,false,I,NaN,V,NaN,7.0,NaN,NaN,False
28092,I,NaN,173,1.0,550.5,2/2,95,11,4,4.0,false,I,NaN,I,NaN,NaN,NaN,NaN,False
28093,V,NaN,174,1.0,554.5,2/2,95,11,4,4.0,false,I,NaN,V,NaN,NaN,NaN,NaN,False
28094,I\\\\,NaN,175,1.0,558.5,2/2,95,11,4,4.0,false,I,NaN,I,NaN,NaN,NaN,NaN,True

Take the above expression and count the chords in all major keys in the cell below.

In [15]:
abc[ abc["local_key"].str.match(major_condition) ]["chord"].value_counts()

I            2567
V7           1597
I6           1375
V            1115
IV            726
             ...
IV(642)         1
vi64(42)        1
V7/II           1
V43(6)/vi       1
iv(b6)          1
Name: chord, Length: 1269, dtype: int64

How would we have to change `major_condition` so that it selects only minor keys? Save the condition for minor keys in a variable `minor_condition` in the cell below.

In [16]:
minor_condition = "^b?[a-z]"

Now, we are in the position to select all minor-key segments from the string quartets and count the chords!

In [17]:
abc[ abc["local_key"].str.match(minor_condition) ]["chord"].value_counts()

i              770
V7             566
V              544
i6             387
I              265
              ...
.bbII.iii        1
V7(2)/bVII       1
.bIII.vii%7      1
i.V(6)           1
#viio2(2)        1
Name: chord, Length: 879, dtype: int64

Compare the first couple of chords in major and minor. Can you interpret it?

**Congratulations! You completely solved the first exercise!**